language: cpp 
os: 
    - linux
compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse"
    - sudo apt-get update

install:
    - if [[ $CXX == 'clang++' ]]; then sudo apt-get install --no-install-recommends clang; fi
    - if [[ $CXX == 'g++'     ]]; then sudo apt-get install --no-install-recommends g++  ; fi
    - sudo apt-get install --no-install-recommends libhdf5-7
    - sudo apt-get install --no-install-recommends -t trusty -y libblitz0-dev libhdf5-serial-dev cmake libboost-python-dev python-numpy libthrust-dev 

    # libcloudphxx
    - cd ..
    - git clone --depth=1 git://github.com/igfuw/libcloudphxx.git
    - cd libcloudphxx
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make
    - sudo make install

script:
    - cd ../../drops.py
    - mkdir build
    - cd build
    - cmake ..
    - make test || cat Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
    - sudo make install
